project:
  type: website
  output-dir: docs
  post-render: encrypt.R

website:
  title: "quarto-private-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
